apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-application
  namespace: tools
spec:
  project: default
  source:
    repoURL: https://github.com/iodine123/microservices-k8s.git
    targetRevision: uat-testing
    path: Deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true