version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8101:8080"  # Map port 8101 on the host to port 8080 in the container
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    deploy:
      replicas: 1
      restart_policy:
        condition: any

volumes:
  jenkins_home:
